### ISSUE TITLE
[Proposal] `when` variant

### ISSUE THREAD

**Issue by bdlukaa** [conceptadev/mix#102]
Mix already has a [long set](https://github.com/conceptadev/mix/blob/466cbce6316fd3970ca6aa3f0a2da646dd57591f/lib/src/variants/variants.dart#L7-L19) of built-in variants. Yet, there isn't a variant to check if a value is true or false: there's where the `when` variant would come in. It'd be similar to the `if` keyword in dart, taking a `bool` as a parameter.

**Basic usage**
```dart
// in a stateful widget

bool hasError = false;

void fetch() {
  try {
    // perform the fetch
    setState(() => hasError = false);
  } catch (e) {
    // handle the error
    setState(() => hasError = true);
  }
}

final mix = Mix(
  when(hasError)(
    bgColor(theme<MyColors>((colors) => colors.errorBackgroundColor)),
  )(
    // this would be the `else` case
    bgColor(theme<MyColors>((colors) => colors.surfaceBackgroundColor)),
  ),
);
```

**Why?**
Currently, it's very verbose to check if a value is true or false in a Mix. We must either ¹create a variant and use `mix.withVariant` or ²create inline conditional checks `hasError ? bgColor(...) : bgColor(...)`

**Comment by leoafarias** [comment]
@bdlukaa I really like that, we do have another conditional which is in the Mix factory `Mix.chooser`, also there is the `variantSwitcher`, The good thing about this approach is that you could nest variant conditionals...

**Comment by bdlukaa** [comment]
From #99 and #93, I also thought of a callback function that may work as a chooser as well:
```dart
Mix(
  bgColor(chooser(hasError)
    (theme<MyColors>((colors) => colors.errorBackgroundColor))
    (theme<MyColors>((colors) => colors.surfaceBackgroundColor)),
  ),
),
```
It'd be used inside the attributes themselves. Of course, would only be possible if #93's model is approved

What are you thoughts on this?
