### ISSUE TITLE
StyledIcon doesn't support decorators attributes

### ISSUE THREAD

**Issue by tilucasoli** [conceptadev/mix#156]
### Package version

branch main and v0.7 too

### Flutter version

```bash
Flutter 3.16.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 78666c8dc5 (4 weeks ago) • 2023-12-19 16:14:14 -0800
Engine • revision 3f3e560236
Tools • Dart 3.2.3 • DevTools 2.28.4
```
### Steps to reproduce

1. Pass the `Style` as a parameter in `StyledIcon` constructor
2. In the `Style` put any attribute that is a decorator

### Expected results

The expected result is the `StyledIcon` receive all attributes and layout it.

### Actual results

The StyledIcon doesn't receive nothing that isn't related to Icon attributes

### Code sample

```dart
import 'package:flutter/material.dart';
import 'package:mix/mix.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: StyledIcon(
        Icons.key,
        style: Style(
          icon.color.red(),
          icon.size(100),
          visibility(false),
        ),
      ),
    );
  }
}

```

**Comment by leoafarias** [comment]
@tilucasoli It's essential to keep in mind that when it comes to supporting decorators for widgets, we must provide the option to set or override the order of the decorator.

https://github.com/conceptadev/mix/blob/9a48d4e5e072bfe624090d31ff465c2de21b4b78/lib/src/specs/container/box_widget.dart#L120C14-L120C14
