### ISSUE TITLE
Shouldn't the PressableBox animate when it possesses the scale attribute?

### ISSUE THREAD

**Issue by tilucasoli** [conceptadev/mix#170]
### Package version

`1.0.0-beta.1`

### Flutter version

```bash
Flutter 3.16.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 67457e669f (9 days ago) • 2024-01-16 16:22:29 -0800
Engine • revision 6e2ea58a5c
Tools • Dart 3.2.5 • DevTools 2.28.5
```

### Steps to reproduce

1. Passing a scale attribute to a Style
2. Placing this Style in the PressableBox's constructor 

### Expected results

![Screen Recording 2024-01-25 at 17 17 54](https://github.com/conceptadev/mix/assets/62367544/3b064de0-1669-48ef-a757-9f377b4d0110)

### Actual results

![Screen Recording 2024-01-25 at 17 21 59](https://github.com/conceptadev/mix/assets/62367544/c3637f26-2f06-435f-b7a3-5c4e3d2fa2d7)

### Code sample

```dart
PressableBox(
  onPressed: () {},
  style: Style(
    backgroundColor.black87(),
    width(80),
    height(50),
    alignment.center(),
    text.style.color.white(),
    scale(1),
    onHover(
      scale(2),
    ),
  ),
  child: const StyledText('Hello'),
)
```

**Comment by tilucasoli** [comment]
This issue is correlated with #167

**Comment by leoafarias** [comment]
This issue has been fixed
