### ISSUE TITLE
Pressable State variants are not working with operators `|` and `&`

### ISSUE THREAD

**Issue by tilucasoli** [conceptadev/mix#232]
### Package version

1.0.0-beta.8

### Flutter version

Flutter 3.16.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 41456452f2 (8 weeks ago) • 2024-01-25 10:06:23 -0800
Engine • revision f40e976bed
Tools • Dart 3.2.6 • DevTools 2.28.5

### Steps to reproduce

Create a logical expression that joins Pressable State Variants, including the types: onHover, onLongPressed, onFocused, and onPressed.

### Expected results

When the expression is satisfied, the style inside the variant's scope will be applied.

### Actual results

The style isn't applied.

### Code sample

```dart

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Center(
        child: PressableBox(
          onPress: () {},
          style: Style(
            backgroundColor.amber(),
            borderRadius(10),
            height(100),
            width(100),
            scale(1.0),
            (onHover | onLongPressed)(
              backgroundColor.blue(),
            ),
          ),
          child: Box(),
        ),
      ),
    );
  }
}
```

**Comment by leoafarias** [comment]
Closed by #235
