### ISSUE TITLE
`onActive` variant?

### ISSUE THREAD

**Issue by loyddaniels** [conceptadev/mix#242]
### Use case

we can annotate the style of a `PressableBox` when it's being hovered on desktop with `onHover`, or provide feedback *after* it's been pressed (not sure what the value of this one is, would love some clarification) with `onPressed`. How do we annotate it's styled *while* the user's finger is down on the screen, *while* pressing the `PressableBox`?

### Proposal

add an `onActive` variant to style the `PressableBox` *while* it's being pressed.

**Comment by tilucasoli** [comment]
Thank you for your contribution. Currently, we are handling the `onTapUp`. The Mix would provide a way to handle other behaviors, such as `onTapDown`. if we create `onPressedDown` and `onPressedUp` variants, it would solve this issue. What do you think about it, @leoafarias?

**Comment by leoafarias** [comment]
On version 1.4 we have implemented an `$on.selected` variant, but it should be implemented as part of the WidgetStateController as you can see here. https://www.fluttermix.com/docs/tutorials/controlling-widget-state
