### ISSUE TITLE
Add cursor styling options via a $mouse function

### ISSUE THREAD

**Issue by jezell** [conceptadev/mix#261]
### Use case

Setting cursor is a bit of a pain since it's not currently supported

### Proposal

```dart
Style(
$mouse.cursor(cursor: SystemMouseCursors.click)
)
```

**Comment by tilucasoli** [comment]
I created a PR adding this attribute, but the syntax is slightly different. To change the mouse appearance you can wrap your widget with a `MouseRegion` and apply a value to the parameter `cursor`, for this reason, I implemented the cursor attribute as a decorator. 

```dart
Box(
   style: Style(
      $box.height(100)
      $box.width(100)
      $box.color(Colors.red)
      $with.cursor.click()
   )
)
```
