### ISSUE TITLE
Add onHover to PressableBox

### ISSUE THREAD

**Issue by jezell** [conceptadev/mix#262]
### Use case

Should be a bit easier to add a hover even callback to the button like you can with onPress

### Proposal

```

final void Function(bool)? onHover

```

**Comment by tilucasoli** [comment]
Hey @jezell, thank you for your contribution. Could you send us a use case explaining a real scenario? What would you like to do with this new property?

**Comment by jezell** [comment]
@tilucasoli change the cursor when someone hovers a button. You can't really use mix on web without injecting web specific wrappers and mouse regions because cursor support is missing.

**Comment by jezell** [comment]
@tilucasoli the specific case we ran into outside of changing the cursor was when we hover a button we need to impact the state of a widget outside the button. When the pointer goes over a button, we need to display a guide in our editor to show what region of the document is going to be changed if you click the button.

**Comment by leoafarias** [comment]
@jezell Version 1.4.0 has `onFocusChange`. We have refactored the Pressable behavior and implemented the WidgetStateController, which you can learn more about here: https://www.fluttermix.com/docs/tutorials/controlling-widget-state

**Comment by jezell** [comment]
@leoafarias thanks, we upgraded to 1.4.0 last week!
