### ISSUE TITLE
InteractiveBox > PressableBox

### ISSUE THREAD

**Issue by jonathanfristedt** [conceptadev/mix#266]
### Use case

A more intuitive name describing the expected capacities of the widget (on hover, pressed, long press etc) while also giving room for further development of the widget

### Proposal

Suggestion to rename PressableBox to InteractiveBox

**Comment by tilucasoli** [comment]
Thank you for your contribution! 

We were discussing it because it was mentioned on another Issue that requested adding one more callback on PressableBox, the onHover. I agree that to continue with the name `PressableBox` is a bit weird.

@leoafarias what's your opinion?

**Comment by leoafarias** [comment]
Yes, this aligns well with our internal discussions, @jonathanfristedt. We might also create a different name for the `Pressable`, which is just a provider of the states and does not have the `Box` styling.

**Comment by leoafarias** [comment]
We now support the WidgetStateController and Interactable which handles these cases described
https://www.fluttermix.com/docs/tutorials/controlling-widget-state
