### ISSUE TITLE
Shorter way to set box size

### ISSUE THREAD

**Issue by Maksimka101** [conceptadev/mix#322]
### Use case

Often, I wan to set both height and width. For now I can do it with either `$box.only(height: 10, width: 10)` or `$box.height(10), $box.width(10)`. Also pretty often I need to create a square which is verbose with current api

### Proposal

Create a new utility to set size with the following api:
```dart
$box.size(10, 20);
$box.size.square(10);
$box.size.as(Size(10, 20));
```

And improve the `$with.sizedBox` by adding the following api:
```dart
$with.sizedBox.square(10);
$with.sizedBox.height(10);
$with.sizedBox.width(10);
$with.sizedBox.as(Size(10, 20));
```

**Comment by definev** [comment]
I think it is bad idea. Utilities should reflecting the specs not add more unwanted information to it. And it's will be a mess real quick like CSS if we add n utilities just for less typing code

**Comment by Maksimka101** [comment]
@definev but that's exactly what you are doing! :)

Okay, I can definitely live with the `$box.only(width: 10, height: 20)` to set different height and width in one line. But in case of square it's disturbing a lot when I need to change size in two places instead of one. The `SizedBox.square` exists for a reason ;)

**Comment by tilucasoli** [comment]
Thank you for your contribution!

I completely agree with you about 'sizedBox' receiving 'height', 'width', and 'square'. However, I'm not a big fan of 'box.size' because it breaks a pattern we are following, keeps the mix API close to the Flutter API, and creates as few aliases as possible.

**Comment by tilucasoli** [comment]
A good thing about mix is that you can create some aliases easily. For Instance, if you prefer to work with `$box.size.height` instead of `$box.height` you can do something like the following code in your project 

```dart
extension on BoxSpecUtility {
  BoxSizeUtility get size => BoxSizeUtility(
        (v) => only(
          height: v.height,
          width: v.width,
        ),
      );
}

class BoxSizeUtility<T extends Attribute>
    extends MixUtility<T, ({double? height, double? width})> {
  late final width = DoubleUtility((v) => call(width: v));
  late final height = DoubleUtility((v) => call(height: v));
  late final square = DoubleUtility((v) => call(height: v, width: v));

  BoxSizeUtility(super.builder);

  T call({double? height, double? width}) => builder((
        height: height,
        width: width,
      ));
}

```
