### ISSUE TITLE
FlexSpecAttribute does not resolve gap.ref()

### ISSUE THREAD

**Issue by qoob23** [conceptadev/mix#326]
### Package version

1.1.0

### Flutter version

Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (3 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3

### Steps to reproduce

Use `$flex.gap.ref()` inside Style

### Expected results

SpaceToken resolves according to MixThemeData from context.

### Actual results

SizedBox inside StyledFlex has negative width because `SpaceToken.resolve()` is never called, and `SpaceToken.call()` returns `hashcode * -1` (which is used in MixTokenResolver and SpaceRef)

### Code sample

<details open><summary>Code sample</summary>

```dart
    return MixTheme(
      data: MixThemeData(spaces: {
        $token.space.small: 8,
      }),
      child: Builder(builder: (context) {
        return StyledFlex(
          direction: Axis.horizontal,
          style: Style(
            $flex.gap.ref($token.space.small), // negative gap
            // $flex.gap($token.space.small.resolve(context)), // works fine
          ),
          children: const [
            Text('Text1'),
            Text('Text2'),
          ],
        );
      }),
    );
```

</details>

**Comment by tilucasoli** [comment]
Thank you for your contribution 😊.

I opened a PR to solve this issue.

**Comment by leoafarias** [comment]
#327 Closes by
