### ISSUE TITLE
Consider exposing onEnd property of underlying AnimatedContainer / AnimatedBoxSpecWidget in Mix

### ISSUE THREAD

**Issue by Kypsis** [conceptadev/mix#343]
### Use case

Would be handy to have access to the `onEnd` property of the underlying widgets that Mix wraps and having the ability to maybe even react to it within Mix. Eg when some container element fades out, toggle its visibility.

### Proposal

Expose the `onEnd` property of the Mix wrapped implicitly named widgets.

**Comment by tilucasoli** [comment]
Solved in #458
