### ISSUE TITLE
Modularize `Pressable` into many smaller features to avoid side-effects

### ISSUE THREAD

**Issue by definev** [conceptadev/mix#366]
### Use case

I have a custom behavior base on `onPan` in `GestureDetector` but when i wrap `GestureDetector` to do it. It's not trigger because of `Pressable` took over it.

### Proposal

We can separate `Pressable` to `Focusable`, `GestureBox` or provide some way to access and manipulate these `onPan` properties

**Comment by leoafarias** [comment]
@definev Pressable in this case behaves closer to a FocusableActionDetector, but I think we probably should allow the ability to override the widgets within, like the focusable and so on. We will take a look at this.
