### ISSUE TITLE
StyledText widget does not retain Font Variations for Variable Fonts

### ISSUE THREAD

**Issue by GiteshDalal** [conceptadev/mix#369]
### Package version

1.2.0

### Flutter version

Flutter 3.22.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5dcb86f68f (9 weeks ago) • 2024-05-09 07:39:20 -0500
Engine • revision f6344b75dc
Tools • Dart 3.4.0 • DevTools 2.34.3

### Steps to reproduce

Create a MixThemeData with TextStyleToken where you are using a variable font.
![image](https://github.com/conceptadev/mix/assets/12757013/c24486e6-7521-48d8-bbc2-2d64f5103b4c)

Create a style with the token
![image](https://github.com/conceptadev/mix/assets/12757013/db677d8c-0400-4754-b70c-eb06c0757c67)

Use the style in the StyledText widget.
FontVariations do not apply.

On debugging, resolved style in TextSpec has null value for fontVariations

### Expected results

FontVariations Value should not be missing in resolved style on TextSpec for StyledText widget.

### Actual results

Rendered text should have FontVariations applied.

### Code sample

```
extension TextStyleTokenUtilExt on TextStyleTokenUtil {
  TextStyleToken get body => const TextStyleToken('text.paragraph');
}

MixThemeData(
  textStyles: {
    $token.textStyle.body: const TextStyle(
    fontFamily: 'RobotoFlex,
    fontSize: 24,
    fontVariations: [
      FontVariation('wgth', 700),
    ],
  },
)
```

```
StyledText('Testing variable font', style: Style(
  $text.style.ref($token.textStyle.body),
))
```

**Comment by tilucasoli** [comment]
Thank you for your contribution ❤️
I opened a PR related to your issue. It will be available in the next release.
