### ISSUE TITLE
Flexible and Align modifiers doesn't work together

### ISSUE THREAD

**Issue by Maksimka101** [conceptadev/mix#373]
### Package version

1.2.0

### Flutter version

3.22.2

### Steps to reproduce

Run the code sample

### Expected results

Box in Align in Flexible. Flexible(child: Align(child: Box()))

### Actual results

The `Incorrect use of ParentDataWidget` error because the Align modifier goes before the Flexible even though it's placed first. That's because of the modifiers default order: Align modifier is listed there but Flexible is not so Flexible is sorted to the end of the modifiers list. 

By the way, I found it very misleading that there is a default modifiers order. It's not mentioned anywhere in docs. And I think the default order it's not always good. For example, what if I want to set the box size and then align it's content? To do so I can't use only `$with` or only `$box`, I must use the `$with.sizedBox` and then `$box.alignment`. `$box.height` and `$with.align` won't work!

In my humble opinion, mix shouldn't have the default ordering. The list of modifiers provided by the developer should be the source of truth. And I don't want to override or disable default ordering all the time! 🙂

Full error message:
```
The ParentDataWidget Flexible(flex: 1) wants to apply ParentData of type FlexParentData to a RenderObject, which has been set up to accept ParentData of incompatible type BoxParentData.
Usually, this means that the Flexible widget has the wrong ancestor RenderObjectWidget. Typically, Flexible widgets are placed directly inside Flex widgets.
The offending Flexible is currently placed inside a Align widget.
The ownership chain for the RenderObject that received the incompatible parent data was:
  SizedBox ← RenderModifiers ← Mix ← Box ← Container ← BoxSpecWidget ← Builder ← Flexible ← Align ← RenderModifiers ← ⋯
```

### Code sample

<details open><summary>Code sample</summary>

```dart
VBox(
  children: [
    Box(
      style: Style(
        $with.expanded(),
        $with.align(alignment: Alignment.center),
      ),
      child: Box(
        style: Style(
          $with.sizedBox.square(50),
          $box.color.red(),
        ),
      ),
    ),
  ],
)
```

</details>

**Comment by Maksimka101** [comment]
The best solution to this problem seems to be adding a flag that will enable or disable the default order of modifiers

**Comment by leoafarias** [comment]
@Maksimka101 You make a good point. We have had discussions about this before, and it seems there would be no perfect solution, but this might be the least imperfect one. I will take a look at the flexible ordering and go from there.
