### ISSUE TITLE
mix_generator 0.2.1 generates bad code

### ISSUE THREAD

**Issue by oscarspalk** [conceptadev/mix#390]
### Package version

0.2.1

### Flutter version

Flutter 3.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b0850beeb2 (4 days ago) • 2024-07-16 21:43:41 -0700
Engine • revision 235db911ba
Tools • Dart 3.4.4 • DevTools 2.34.3

### Steps to reproduce

I simply followed the original [tutorial](https://www.fluttermix.com/docs/tutorials/creating-a-widget)

### Expected results

The generator should produce compilable code

### Actual results

The generator misses some import statements or something resulting in non-compilable code

### Code sample

^^

**Comment by nacho-bytes** [comment]
I have the same issue as @oscarspalk points here. For my particular usecase:

- When using a property Color in the MyWidgetSpec the generated code produces an error and a warning per property in the MyWidgetSpecAttribute class.

The warning is in the generation of the `merge` method as this code:

```dart
final class KnobSpecAttribute extends SpecAttribute<KnobSpec>
    with Diagnosticable {

  ...

  @override
  MyWidgetSpecAttribute merge(MyWidgetSpecAttribute? other) {
    if (other == null) return this;

    return MyWidgetSpecAttribute (
      /* 
         The below line throws the next warning:
         The method 'merge' can't be unconditionally invoked because the receiver can be 'null'.
         Try making the call conditional (using '?.') or adding a null check to the target ('!').dart[unchecked_use_of_nullable_value (https://dart.dev/diagnostics/unchecked_use_of_nullable_value)
      */
      backgroundColor: backgroundColor.merge(other.backgroundColor) ?? other.backgroundColor,
      animated: animated?.merge(other.animated) ?? other.animated,
    );
  }

  ...

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    /*
       All both lines throw the next error:
       The method 'addUsingDefault' isn't defined for the type 'DiagnosticPropertiesBuilder'.
       Try correcting the name to the name of an existing method, or defining a method named 'addUsingDefault'.dart[undefined_method](https://dart.dev/diagnostics/undefined_method)
    */
    properties.addUsingDefault('backgroundColor', backgroundColor);
    properties.addUsingDefault('animated', animated);
  }
}
```

I hope this can be fixed. If I could help in any way just tell me. Thank you in advance.

**Comment by oscarspalk** [comment]
I made a very rapid [pr](https://github.com/conceptadev/mix/pull/392), it fixes these issues, but you still have to manually import some stuff in the source for the generated file.
