### ISSUE TITLE
Website Dead link

### ISSUE THREAD

**Issue by Solido** [conceptadev/mix#442]
### Steps to reproduce

Click on _custom component_ at the bottom of the page
https://www.fluttermix.com/docs/widgets/introduction#styleimage

https://www.fluttermix.com/docs/tutorials/custom-component => 404

### Expected results

page display

### Actual results

404

### Code sample

`No need for code`

**Comment by tilucasoli** [comment]
Thank you for your contribution ❤️ 
I've just fixed it. Could you try again?

**Comment by Solido** [comment]
Resolved!
