### ISSUE TITLE
Shortcut for borderColor and others Mix properties

### ISSUE THREAD

**Issue by VladimirCores** [conceptadev/mix#83]
Would love to have:
```
bgColor -> bgc
border -> br
borderColor -> brc
borderWidth -> brw
borderStyle -> brs
rounded -> rd
squared -> sq
shadow -> sh
```
and similar to others.

**Comment by bdlukaa** [comment]
Rounded already has `r` as a shortcut

**Comment by leoafarias** [comment]
@VladimirCores We tried to do short versions for everything but it started to hurt the dev experience and also create overlap between different ones, that is why we created for main ones only. But if you want creating some of these items is easy enough by just reassining

Example
`final rd = rounded`

**Comment by VladimirCores** [comment]
All right, I'll do it if needed, thanks for suggestion ;)
